# Generated by Django 5.1.2 on 2024-11-21 20:05

from django.db import migrations, models
import datetime



class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
