# Generated by Django 5.1.2 on 2024-11-21 20:05

from django.db import migrations, models
import datetime



class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_position_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
