# Generated by Django 5.1.2 on 2024-11-21 20:51

from django.db import migrations, models
import datetime



class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_employee_emailaddress_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
