# Generated by Django 5.1.2 on 2024-10-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invetory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
